### ISSUE TITLE
Can you add some documentation and examples for usages?

### ISSUE THREAD

**Issue by li-xin-yi** [aengelke/instrew#4]
Hi, I'm really impressed by [your talk](https://www.youtube.com/watch?v=gBijjM_N9Mk&t) and want to try `instrew` by myself. But I am stuck at few explanations of the usages. After I installed `instrew`, I don't even know how to use it. Can you provide some `readme` documentation or `--help` option for it? Or can you tell me how to investigate, and I will do whatever I can to complete the document work for this project?

Thank you very much.

**Comment by younghojan** [comment]
Have you built Instrew successfully? I have built it on Ubuntu 22.10, but its example for testing cannot be executed by Instrew. It returned "unhandled syscall 262".

**Comment by aengelke** [comment]
I just pushed a readme update with usage instructions and made a few other changes -- I hope this helps. The unhandled syscall messages are often caused by new glibc versions trying to use recent system calls, that are not yet supported -- syscall support is developed highly demand-driven, so if there's something missing, please create an issue for that.
